= Parameters

The parent key for all of the following parameters is `cluster_backup`.


== `enabled`

[horizontal]
type:: bool
default:: `true`

Whether to create the ArgoCD app for the component.
Setting this to false, effectively disables the component from being deployed.

NOTE: The manifests will still appear in the catalog, but without the ArgoCD app they won't get deployed.

== `namespace`

[horizontal]
type:: string
default:: `syn-cluster-backup`

The namespace in which to deploy this component.

== `bucket`

[horizontal]
type:: dictionary

Holds the name and credentials for an S3 type storage bucket.
This bucket will be used to store the backups.

=== `accesskey`

[horizontal]
type:: string
default:: `'?{vaultkv:${customer:name}/${cluster:name}/cluster-backup/s3_access_key}'`

The access key needed to access the storage bucket.
The default is a reference to a secret within Vault.

=== `name`

[horizontal]
type:: string
default:: `${cluster:name}-cluster-backup`

The name of the storage bucket.

=== `secretkey`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/cluster-backup/s3_secret_key}`

The secret key needed to access the storage bucket.
The default is a reference to a secret within Vault.

== `images`

[horizontal]
type:: dictionary

Dictionary holding the container image versions used by this component.

=== `object_dumper`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
image: docker.io/projectsyn/k8s-object-dumper
tag: latest
----

Object dumper is script that exports all retreivalbe objects from a Kubernetes API and dumps them as a Tar archive.
See https://github.com/projectsyn/k8s-object-dumper.

=== `keepjobs`

[horizontal]
type:: number
default:: `5`

Number of backup jobs to keep.

== `password`

[horizontal]
type:: string
default:: `?{vaultkv:${customer:name}/${cluster:name}/cluster-backup/password}'`

Password used to encrypt the backup.
The default is a reference to a secret within Vault.

== `known_to_fail`

[horizontal]
type:: list
default::
+
[source,yaml]
----
- '.+mutators'
- '.+reviews'
- '.+validators'
- 'bindings'
- 'deploymentconfigrollbacks'
- 'imagesignatures'
- 'imagestreamimages'
- 'imagestreamimports'
- 'imagestreammappings'
- 'mutations'
- 'projectrequests'
- 'useridentitymappings'
- 'validations'
----

Resource types which are known as producing errors when doing `kubectl get <resource>`.

== `must_exist`

[horizontal]
type:: list
default::
+
[source,yaml]
----
- 'configmaps'
- 'daemonsets'
- 'deployments'
- 'endpoints'
- 'horizontalpodautoscalers'
- 'ingresses'
- 'jobs'
- 'limitranges'
- 'namespaces'
- 'nodes'
- 'persistentvolumeclaims'
- 'persistentvolumes'
- 'replicasets'
- 'resourcequotas'
- 'roles'
- 'secrets'
- 'serviceaccounts'
- 'services'
- 'statefulsets'
----

Resource types which must exist on any Kubernetes cluster.

== Example

[source,yaml]
----
parameters:
  cluster_backup:
    images:
      object_dumper:
        tag: v…
----
